image:
  repository: microservice-vote
  tag: latest
  pullPolicy: IfNotPresent
  license: ""

  extraEnvs:
  - name: "isAppDown"
    value: "false"

ingress:
  enabled: true
  rewriteTarget: "/openapi/ui"
  path: "/vote"
  host: ""
  secretName: ""

microprofile:
  health:
    enabled: true
